### ISSUE TITLE
From 3.x.x to 4.x.x download old deps

### ISSUE THREAD

**Issue by KrakenTyio** [darekf77/ng2-logger#56]
When i want to upgrade form 3 to 4, its download too many old and deprecated deps
also its try to run node gyp by python,

install log
```
Upgrading .../package.json
[====================] 129/129 100%

 ng2-logger  ~3.0.14  →  ~4.0.3   

Run npm install to install new versions.

stano@stano-NUC:~/projects/docker/cross-sandbox$ npm install
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated @angular/http@7.2.15: Package no longer supported. Use @angular/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated @types/chokidar@2.1.3: This is a stub types definition. chokidar provides its own type definitions, so you do not need this installed.
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated angular-tree-component@7.2.1: Library moved to @circlon/angular-tree-component
npm WARN deprecated @types/systeminformation@3.54.1: This is a stub types definition. systeminformation provides its own type definitions, so you do not need this installed.
npm WARN deprecated express-fileupload@0.4.0: Please upgrade express-fileupload to version 1.1.8+ due to a security vulnerability with the parseNested option
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated letsencrypt@2.1.10: letsencrypt has been renamed to greenlock. Please find it at npm greenlock
npm WARN deprecated safetimeout@0.1.2: Please use the 'safe-timers' module instead
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.60.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated har-validator@1.8.0: this library is no longer supported
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

> fibers@5.0.0 install /home/node/app/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-83-glibc` exists; testing
Binary is fine; exiting

> cpuid@0.1.3 install /home/node/app/node_modules/cpuid
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> deasync@0.1.20 install /home/node/app/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting

> sqlite3@4.0.9 install /home/node/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.9/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.9 and node@14.7.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 5.6.0-1032-oem
gyp ERR! command "/usr/local/bin/node" "/home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/node/app/node_modules/sqlite3
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/node/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.6.0-1032-oem
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/node/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/node/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/node/app/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN notsup Unsupported engine for karma-cli@1.0.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"14.7.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: karma-cli@1.0.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/morphi/node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for karma-cli@1.0.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"14.7.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: karma-cli@1.0.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/bs4-breakpoint/node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.0.6 (node_modules/incremental-compiler/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/ng-packagr/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for karma-cli@1.0.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"14.7.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: karma-cli@1.0.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/tnp-db/node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for karma-cli@1.0.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"14.7.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: karma-cli@1.0.1
npm WARN @agm/core@1.1.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @agm/core@1.1.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@10.2.1 requires a peer of zone.js@~0.10.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-unicorn@0.5.0 requires a peer of eslint@^4.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-unicorn@0.5.0 requires a peer of eslint-plugin-node@^5.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-unicorn@0.5.0 requires a peer of eslint-plugin-prettier@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-unicorn@0.5.0 requires a peer of eslint-plugin-react@^7.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-unicorn@0.5.0 requires a peer of prettier@^1.7.4 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-etc@1.0.2 requires a peer of @typescript-eslint/parser@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-rxjs@0.0.2-beta.28 requires a peer of @typescript-eslint/parser@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-rxjs@0.0.2-beta.28 requires a peer of typescript@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-selenium-webdriver-launcher@0.0.4 requires a peer of selenium-webdriver@^2.44.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils-etc@1.3.1 requires a peer of tsutils@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/core@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/platform-browser@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@9.2.4 requires a peer of @angular/cdk@9.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@9.2.4 requires a peer of tslib@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/service-worker@9.1.12 requires a peer of @angular/core@9.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/service-worker@9.1.12 requires a peer of @angular/common@9.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/service-worker@9.1.12 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-formly/ionic@5.10.6 requires a peer of @ionic/angular@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@16.1.1 requires a peer of @angular/common@<9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@16.1.1 requires a peer of @angular/core@<9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-datatable@16.1.1 requires a peer of @angular/platform-browser@<9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-tree-component@7.2.1 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@5.7.1 requires a peer of @angular/compiler@^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@5.7.1 requires a peer of @angular/compiler-cli@^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@5.7.1 requires a peer of tslib@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-packagr@5.7.1 requires a peer of typescript@>=2.7 <3.6 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-breadcrumbs@0.0.3 requires a peer of @angular/core@>=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-breadcrumbs@0.0.3 requires a peer of @angular/router@>=4.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-editor@4.1.0 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-editor@4.1.0 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-editor@4.1.0 requires a peer of @angular/forms@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-editor@4.1.0 requires a peer of ngx-bootstrap@^3.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-editor@4.1.0 requires a peer of rxjs@~6.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-wig@8.1.0 requires a peer of @angular/common@^8.2.13 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-wig@8.1.0 requires a peer of @angular/core@^8.2.13 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-wig@8.1.0 requires a peer of @angular/forms@^8.2.13 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-wig@8.1.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.26.0 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@angular-devkit/build-angular/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-11-04T10_39_05_681Z-debug.log
```

my package.json
```
{
  ...
  "dependencies": {
    "@agm/core": "~1.1.0",
    "@angular/animations": "~10.2.1",
    "@angular/cdk": "~10.2.7",
    "@angular/common": "~10.2.1",
    "@angular/compiler": "~10.2.1",
    "@angular/core": "~10.2.1",
    "@angular/forms": "~10.2.1",
    "@angular/localize": "~10.2.1",
    "@angular/platform-browser": "~10.2.1",
    "@angular/platform-browser-dynamic": "~10.2.1",
    "@angular/router": "~10.2.1",
    "@ckeditor/ckeditor5-angular": "^2.0.1",
    "@ckeditor/ckeditor5-build-classic": "github:bart-sk/ckeditor5-build-classic",
    "@ngrx/effects": "~10.0.1",
    "@ngrx/store": "~10.0.1",
    "core-js": "~3.6.5",
    "create-hmac": "~1.1.7",
    "croppie": "~2.6.5",
    "dom-autoscroller": "~2.3.4",
    "dwt": "~16.1.2",
    "file-saver": "~2.0.2",
    "luxon": "~1.25.0",
    "md5": "~2.3.0",
    "moment": "~2.29.1",
    "moment-timezone": "~0.5.31",
    "normalize.css": "~8.0.1",
    "ng2-logger": "~4.0.3",
    "ngx-clipboard": "~14.0.1",
    "node-interval-tree": "~1.3.3",
    "pdfmake": "~0.1.68",
    "perfect-scrollbar": "~1.5.0",
    "resize-observer-polyfill": "~1.5.1",
    "rrule": "~2.6.6",
    "rxjs": "~6.6.3",
    "socket.io-client": "~2.3.1",
    "sortablejs": "~1.12.0",
    "trust1connector": "~3.0.0",
    "tslib": "~2.0.3",
    "xlsx": "~0.16.8",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "~10.0.1",
    "@angular-devkit/build-angular": "~0.1002.0",
    "@angular/cli": "~10.2.0",
    "@angular/compiler-cli": "~10.2.1",
    "@angular/language-service": "~10.2.1",
    "@ngrx/store-devtools": "~10.0.1",
    "@ngtools/webpack": "~10.2.0",
    "@testing-library/angular": "~10.1.3",
    "@testing-library/user-event": "~12.2.0",
    "@types/core-js": "~2.5.4",
    "@types/create-hmac": "~1.1.0",
    "@types/croppie": "~2.5.5",
    "@types/dwt": "~16.1.1",
    "@types/file-saver": "~2.0.1",
    "@types/googlemaps": "~3.40.3",
    "@types/hammerjs": "~2.0.36",
    "@types/jasmine": "~3.6.1",
    "@types/jasminewd2": "~2.0.8",
    "@types/karma": "~5.0.1",
    "@types/lodash-es": "~4.17.3",
    "@types/md5": "~2.2.1",
    "@types/mocha": "~8.0.3",
    "@types/modernizr": "~3.5.3",
    "@types/new-relic-browser": "~0.1118.0",
    "@types/node": "~14.14.6",
    "@types/pdfmake": "~0.1.16",
    "@types/socket.io-client": "~1.4.34",
    "@types/sortablejs": "~1.10.6",
    "@types/svg-sprite-loader": "~3.9.2",
    "@types/terser-webpack-plugin": "~5.0.2",
    "@types/webpack": "~4.41.24",
    "@types/webpack-dev-server": "~3.11.1",
    "@types/webpack-env": "~1.15.3",
    "@types/webpack-merge": "~4.1.5",
    "@types/youtube": "~0.0.39",
    "@typescript-eslint/eslint-plugin": "~4.6.1",
    "@typescript-eslint/parser": "~4.6.1",
    "base64-js": "~1.3.1",
    "browserstack-local": "~1.4.8",
    "chalk": "~4.1.0",
    "codelyzer": "~6.0.1",
    "cross-env": "~7.0.2",
    "eslint": "~7.12.1",
    "eslint-config-prettier": "~6.15.0",
    "eslint-config-unicorn": "~0.5.0",
    "eslint-plugin-ngrx": "~1.10.2",
    "eslint-plugin-prettier": "~3.1.4",
    "eslint-plugin-unicorn": "~23.0.0",
    "husky": "~4.3.0",
    "jasmine": "~3.6.3",
    "jasmine-core": "~3.6.0",
    "jasmine-reporters": "~2.3.2",
    "jasmine-spec-reporter": "~6.0.0",
    "junit": "~1.4.9",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "~1.5.4",
    "karma-junit-reporter": "~2.0.1",
    "karma-mocha-reporter": "~2.2.5",
    "karma-selenium-webdriver-launcher": "~0.0.4",
    "lint-staged": "~10.5.1",
    "lodash-es": "~4.17.15",
    "mobile-detect": "~1.4.4",
    "moment-locales-webpack-plugin": "~1.2.0",
    "moment-timezone-data-webpack-plugin": "~1.3.0",
    "ngx-i18nsupport": "~0.17.1",
    "parallel-webpack": "~3.0.0-alpha.2",
    "prettier": "~2.1.2",
    "prettier-eslint": "~11.0.0",
    "protractor": "~7.0.0",
    "protractor-beautiful-reporter": "~1.3.6",
    "protractor-fail-fast": "~3.1.0",
    "rxjs-tslint-rules": "~4.34.3",
    "sass": "~1.28.0",
    "source-map-support": "~0.5.19",
    "stylelint": "~13.7.2",
    "stylelint-config-prettier": "~8.0.2",
    "stylelint-config-standard": "~20.0.0",
    "svg-sprite-loader": "~5.0.0",
    "svg-transform-loader": "~2.0.13",
    "svgo": "~1.3.2",
    "svgo-loader": "~2.2.1",
    "tslint": "~6.1.3",
    "tslint-config-prettier": "~1.18.0",
    "tslint-jasmine-rules": "~1.6.1",
    "typescript": "~4.0.5",
    "url-loader": "~4.1.1"
  }
}
```

**Comment by darekf77** [comment]
Hi @KrakenTyio I see you are installing all dependencies (and devDependencies) with `npm install` ... for now try  `npm install --only=prod`  (https://stackoverflow.com/a/9276112/1345101) 

... today I will remove devDependencies from bundle..

I am trying to develop many packages at the same time and I need devDependencies..
but now I see there is a big problem for npm installation for most users...

I will fix this today.. Thanks for opening the issue.



![image](https://user-images.githubusercontent.com/7131693/98215936-b3d32e00-1f48-11eb-9cc4-011807dc5cff.png)

**Comment by darekf77** [comment]
@KrakenTyio try 4.0.5 should be ok.

**Comment by KrakenTyio** [comment]
loogs ok in 4.0.7
